apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.sample.yaml --controller deployment --out k8s-manifests
    kompose.version: 1.22.0 (HEAD)
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.sample.yaml --controller deployment --out k8s-manifests
        kompose.version: 1.22.0 (HEAD)
      labels:
        io.kompose.service: worker
    spec:
      containers:
        - args:
            - celery
            - -A
            - glitchtip
            - worker
            - -B
            - -l
            - INFO
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/postgres
            - name: PORT
              value: "8000"
            - name: SECRET_KEY
              value: postgres
          image: glitchtip/glitchtip
          name: worker
          resources:
            requests:
              cpu: 100m
              memory: 500M
            limits:
              memory: 1G
              cpu: 200m
      restartPolicy: Always
